version: '3.8'

services:
  server:
    image: fastapi_rest:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "80:8000"

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=1
#
#  db:
#    image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#
#volumes:
#  postgres_data: