name: Deploy application

on:
  workflow_run:
    workflows: [ "Continuous integration" ]
    types:
      - completed
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo ${{ secrets.GH_PSW }} | docker login -u ${{ secrets.GH_USR }} --password-stdin
      - name: prepare image
        run: |
          docker-compose build server
          docker tag fastapi_rest ${{ secrets.GH_USR }}/rest_api
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.GH_USR }}/rest_api
